# Generated by Django 6.1.1 on 2026-09-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('project', 'Project'), ('conversation', 'Conversation'), ('goal', 'Goal')], default='fact', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('importance', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
