# Generated by Django 6.1.1 on 2026-09-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('guest', 'Guest'), ('registered', 'Registered'), ('premium', 'Premium'), ('admin', 'Admin')], default='registered', max_length=20)),
                ('daily_messages', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
